# Generated by Django 3.1.7 on 2021-03-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files_data',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='files_data',
            name='ADDRESS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files_data',
            name='BANK',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='files_data',
            name='BRANCH',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='files_data',
            name='CITY1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='files_data',
            name='CITY2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='files_data',
            name='IFSC',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='files_data',
            name='MICR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files_data',
            name='PHONE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files_data',
            name='STATE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='files_data',
            name='STD',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
