# Generated by Django 3.1.7 on 2021-03-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_auto_20210316_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_data',
            name='MICR',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
